-- 2단계: 서버 API 전용 자료 테이블. 메모 본문은 이 공개 파일에 넣지 않습니다.
begin;
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);
alter table public.notes enable row level security;
revoke all on table public.notes from public, anon, authenticated;
grant select, insert, update, delete on table public.notes to service_role;
grant usage, select on sequence public.notes_id_seq to service_role;
-- owner_id는 다음 로그인 단계에서 연결합니다. auth.users 외래키는 아직 없습니다.
-- anon/authenticated용 SELECT 정책을 만들지 않습니다.
commit;
